version: "3.9"

volumes:
  node_modules_practice_github_react:

services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: practice_github_react
    tty: true
    volumes:
      - .:/app
      - node_modules_practice_github_react:/app/frontend/node_modules
    ports:
      - 5183:5173
    command: yarn dev
